
  CREATE TABLE "CUSTOMERS"
   (	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CUSTOMER_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255),
	"PHONE" VARCHAR2(20),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

