
  CREATE TABLE "ORDER_ITEMS"
   (	"ORDER_ITEM_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"PRODUCT_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"QUANTITY" NUMBER(10,0) NOT NULL ENABLE,
	"UNIT_PRICE" NUMBER(12,2) NOT NULL ENABLE,
	"LINE_TOTAL" NUMBER(12,2) NOT NULL ENABLE,
	 CONSTRAINT "PK_ORDER_ITEMS" PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_ORDER_ITEMS_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERS" ("ORDER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

