
  CREATE TABLE "ORDERS"
   (	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ORDER_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SHIP_DATE" DATE,
	"DELIVERY_DATE" DATE,
	"TOTAL_AMOUNT" NUMBER(12,2) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_ORDERS_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

