
  CREATE TABLE "SHIPPING_ADDRESSES"
   (	"ADDRESS_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ADDRESS_LINE1" VARCHAR2(200) NOT NULL ENABLE,
	"ADDRESS_LINE2" VARCHAR2(200),
	"CITY" VARCHAR2(100) NOT NULL ENABLE,
	"STATE" VARCHAR2(50),
	"POSTAL_CODE" VARCHAR2(20),
	"COUNTRY" VARCHAR2(100) DEFAULT 'USA' NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1) DEFAULT 'N',
	 CONSTRAINT "CHK_IS_DEFAULT" CHECK (IS_DEFAULT IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "PK_SHIPPING_ADDRESSES" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_SHIPPING_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

